# Generated by Django 2.0.2 on 2020-11-23 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_rental_issue_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='price',
        ),
    ]
