# Generated by Django 2.0.2 on 2020-11-24 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0007_remove_rental_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='due_date',
        ),
    ]
