# Generated by Django 2.0.2 on 2020-11-24 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0008_remove_rental_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='qtyUnit',
        ),
    ]
