# Generated by Django 2.0.2 on 2020-11-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0009_remove_rental_qtyunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
