# Generated by Django 2.0.2 on 2020-11-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0010_rental_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='requested',
            field=models.BooleanField(default=True),
        ),
    ]
