# Generated by Django 2.0.2 on 2020-11-27 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0011_rental_requested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='requested',
            new_name='approved',
        ),
    ]
