# Generated by Django 2.0.2 on 2020-11-27 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0013_auto_20201127_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='approved',
            new_name='returned',
        ),
    ]
