# Generated by Django 2.0.2 on 2020-11-27 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0014_auto_20201127_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='returned',
            new_name='approved',
        ),
    ]
